bd_path: data/main.db
test_bd_path: data/test.db

initial_user_money: 10000
predicted_score_coeff: 3

menu_naming:
  user_registration: Зарегистрироваться
  show_matches: Показать матчи
  show_match_info: Показать информацию о матче
  refresh_score: Обновить счет
  refresh_rates: Обновить коэффициенты
  make_bet: Сделать ставку
  show_leaderboard: Показать Лидерборд
  show_user_bets: Показать ваши ставки
  add_match: Добавить матч
  show_match_bets: Показать ставки игроков на этот матч
