bd_path: data/main.db
test_bd_path: data/test.db

initial_user_money: 10000
predicted_score_coeff: 3

admins_list: [46340594]

menu_naming:
  back_to_menu: В меню
  user_registration: Зарегистрироваться
  show_matches: Показать матчи
  show_finished_matches: Показать завершившиеся матчи
  show_match_info: Показать информацию о матче
  refresh_score: Обновить счет
  refresh_rates: Обновить коэффициенты
  refresh_team_names: Обновить названия команд
  make_bet: Сделать ставку
  show_leaderboard: Показать Лидерборд
  show_user_bets: Показать ваши ставки
  add_match: Добавить матч
  show_match_bets: Показать ставки игроков на этот матч
  show_current_user_bets: Показать ставки игрока

flags:
  ECU:
    code2: EC
    name: Ecuador
  SEN:
    code2: SN
    name: Senegal
  NLD:
    code2: NL
    name: Netherlands
  QAT:
    code2: QA
    name: Qatar
  USA:
    code2: US
    name: United States of America
  IRN:
    code2: IR
    name: Iran
  MEX:
    code2: MX
    name: Mexico
  SAU:
    code2: SA
    name: Saudi Arabia
  ARG:
    code2: AR
    name: Argentina
  POL:
    code2: PL
    name: Poland
  FRA:
    code2: FR
    name: France
  DNK:
    code2: DK
    name: Denmark
  TUN:
    code2: TN
    name: Tunisia
  AUS:
    code2: AU
    name: Australia
  DEU:
    code2: DE
    name: Germany
  JPN:
    code2: JP
    name: Japan
  ESP:
    code2: ES
    name: Spain
  CRI:
    code2: CR
    name: Costa Rica
  HRV:
    code2: HR
    name: Croatia
  MAR:
    code2: MA
    name: Morocco
  CAN:
    code2: CA
    name: Canada
  BEL:
    code2: BE
    name: Belgium
  SRB:
    code2: RS
    name: Serbia
  CHE:
    code2: CH
    name: Switzerland
  BRA:
    code2: BR
    name: Brazil
  CMR:
    code2: CM
    name: Cameroon
  KOR:
    code2: KR
    name: Korea
  PRT:
    code2: PT
    name: Portugal
  GHA:
    code2: GH
    name: Ghana
  URY:
    code2: UY
    name: Uruguay
  TUR:
    code2: TR
    name: Türkiye
  SWE:
    code2: SE
    name: Sweden
  ALB:
    code2: AL
    name: Albania
  ARM:
    code2: AM
    name: Armenia
  CZE:
    code2: CZ
    name: Czechia
  DZA:
    code2: DZ
    name: Algeria


